### ISSUE TITLE
Bugs with furniture functionality (advfort)

### ISSUE THREAD

**Issue by adamkad1** [warmist/dfhack#4]
Trying to eat on a seat only only works (can put item into reaction) when its in inv, not in hands, and it puts it into "hauling" but then the timer is stuck at -1, like plant gathering
Trying to sleep in bed will be interrupted by -dangerous after pressing "." (and "," too mayby?)

**Comment by lethosor** [comment]
Isn't advfort in the main repo too? Is there a reason you opened this here instead?

**Comment by adamkad1** [comment]
i came here from link of adv fort thread on bay's forum. seemed legit. Everything else regarding adv fort is stuck in the DFhack/dfhack repo but then, shouldnt that link lead there?
